"""initial schema

Revision ID: ba7340a79aa5
Revises: 
Create Date: 2026-04-22 11:19:22.994729
"""
from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision = 'ba7340a79aa5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('raw_texts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=100), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('source_url', sa.String(length=500), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_raw_texts_id'), 'raw_texts', ['id'], unique=False)
    op.create_index(op.f('ix_raw_texts_source'), 'raw_texts', ['source'], unique=False)
    op.create_table('analyzed_sentiments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('raw_text_id', sa.Integer(), nullable=False),
    sa.Column('overall_sentiment', sa.String(length=50), nullable=False),
    sa.Column('confidence_positive', sa.Float(), nullable=False),
    sa.Column('confidence_neutral', sa.Float(), nullable=False),
    sa.Column('confidence_negative', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['raw_text_id'], ['raw_texts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('raw_text_id')
    )
    op.create_index(op.f('ix_analyzed_sentiments_id'), 'analyzed_sentiments', ['id'], unique=False)
    op.create_index(op.f('ix_analyzed_sentiments_overall_sentiment'), 'analyzed_sentiments', ['overall_sentiment'], unique=False)
    op.create_table('opinion_targets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('analyzed_sentiment_id', sa.Integer(), nullable=False),
    sa.Column('target_name', sa.String(length=200), nullable=False),
    sa.Column('target_sentiment', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['analyzed_sentiment_id'], ['analyzed_sentiments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_opinion_targets_analyzed_sentiment_id'), 'opinion_targets', ['analyzed_sentiment_id'], unique=False)
    op.create_index(op.f('ix_opinion_targets_id'), 'opinion_targets', ['id'], unique=False)
    op.create_index(op.f('ix_opinion_targets_target_name'), 'opinion_targets', ['target_name'], unique=False)
    op.create_index(op.f('ix_opinion_targets_target_sentiment'), 'opinion_targets', ['target_sentiment'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_opinion_targets_target_sentiment'), table_name='opinion_targets')
    op.drop_index(op.f('ix_opinion_targets_target_name'), table_name='opinion_targets')
    op.drop_index(op.f('ix_opinion_targets_id'), table_name='opinion_targets')
    op.drop_index(op.f('ix_opinion_targets_analyzed_sentiment_id'), table_name='opinion_targets')
    op.drop_table('opinion_targets')
    op.drop_index(op.f('ix_analyzed_sentiments_overall_sentiment'), table_name='analyzed_sentiments')
    op.drop_index(op.f('ix_analyzed_sentiments_id'), table_name='analyzed_sentiments')
    op.drop_table('analyzed_sentiments')
    op.drop_index(op.f('ix_raw_texts_source'), table_name='raw_texts')
    op.drop_index(op.f('ix_raw_texts_id'), table_name='raw_texts')
    op.drop_table('raw_texts')
    # ### end Alembic commands ###
